data_source:
  EDGES: gs://bucket/edges
  COMPONENTS: gs://bucket/components
  WATERSHED: gs://bucket/ws

graph_config:
  CHUNK_SIZE: [512, 512, 128]
  FANOUT: 2
  SPATIAL_BITS: 10
  LAYER_ID_BITS: 8

backend_client:
  TYPE: bigtable
  CONFIG:
    ADMIN: true
    READ_ONLY: false

mesh_config:
  dir: graphene_meshes
  dynamic_mesh_dir: "dynamic"
  mip: 0
  max_layer: 6
  max_error: 40
  chunk_size: [512, 512, 256]
  minishard_bits: {2: 1, 3: 3, 4: 6, 5: 9, 6: 12}
